// lib/React/Button/Button.tsx
import { type ReactNode } from 'react';
import { type ButtonProps as BaseButtonProps, getFinalClassName } from '../../globals/Button';

export interface ButtonProps
  extends Omit<React.HTMLAttributes<HTMLButtonElement>, 'color' | 'className'>,
    BaseButtonProps {
  children: ReactNode;
}

export const Button = ({ children, className, color = 'default', size = 'medium', action, ...props }: ButtonProps) => {
  const buttonClasses = getFinalClassName(action, color, size, className);

  return (
    <button className={buttonClasses} {...props}>
      {children}
    </button>
  );
};

// lib/Svelte/Button/Button.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLButtonAttributes } from 'svelte/elements';
  import {
    type ButtonProps,
    getFinalClassName
  } from '../../globals/Button';

  interface Props extends ButtonProps, Omit<HTMLButtonAttributes, 'color' | 'class' | 'children'> {
    children: Snippet | string;
  }

  const {
    action,
    color = 'default',
    size = 'medium',
    className,
    children,
    onclick,
    ...props
  }: Props = $props();

  const buttonClasses = $derived(
    getFinalClassName(action, color, size, className)
  );
</script>

{#snippet content()}
  {#if typeof children === 'string'}
    {children}
  {:else}
    {@render children?.()}
  {/if}
{/snippet}

<button class={buttonClasses} {onclick} {...props}>
  {@render content()}
</button>
